services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: produksjonsplass
    volumes:
      - ./database:/docker-entrypoint-initdb.d
