spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produksjonsplass
    username: docker
    password: docker

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
